[package]
name = "gradio_macro_test"
version = "0.1.0"
edition = "2021"

[dependencies]
gradio = "0.2"
serde_json = "1.0.127"
gradio_macro = { path = "gradio_macro" }
anyhow = "1.0.86"
serde = "1.0.209"

[features]
gen_api=[]
