[package]
name = "gradio_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
gradio = "0.2.4"
proc-macro2 = "1.0"
quote = "1.0.37"
regex = "1.10.6"
serde = "1.0.209"
serde_json = "1.0.127"
syn = "2.0.76"

[lib]
proc-macro = true
